server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: MovieService
  profiles:
    active: db

#  datasource:
#    url: jdbc:postgresql://localhost:5432/movie
#    username: postgres
#    password: postgres
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

#eureka:
#  instance:
#    client:
#      serviceUrl:
#        defaultZone: http://localhost:8761/eureka/
logging:
  file:
    name: C://work/app/app.log
  level:
    org.springframework.web: INFO
    org.hibernate: ERROR

