server:
  port: 8084
  servlet:
    context-path: /api/v1
  ssl:
    key-alias: coda
    key-store: classpath:KeyStore.jks
    key-store-password: 13047804kl
    key-store-type: JKS
spring:
  application:
    name: MovieService
  profiles:
    active: db

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

#eureka:
#  instance:
#    client:
#      serviceUrl:
#        defaultZone: http://localhost:8761/eureka/
logging:
  file:
    name: C://work/app/app.log
  level:
    org.springframework.web: INFO
    org.hibernate: ERROR

